# Generated by Django 4.0.4 on 2022-05-21 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Title')),
                ('link', models.URLField(verbose_name='Link')),
                ('archived_flag', models.BooleanField(default=False, verbose_name='Archived')),
                ('deleted_flag', models.BooleanField(default=False, verbose_name='Deleted')),
                ('new_flag', models.BooleanField(default=True, verbose_name='New')),
                ('obsoleted_flag', models.BooleanField(default=False, verbose_name='Obsoleted')),
                ('creation_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation At')),
                ('modification_at', models.DateTimeField(auto_now=True, verbose_name='Modification At')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
